# Generated by Django 6.1 on 2026-08-28 22:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('price_min', models.PositiveIntegerField(help_text='Monthly price, lower bound')),
                ('price_max', models.PositiveIntegerField(help_text='Monthly price, upper bound')),
                ('room_type', models.CharField(blank=True, choices=[('putra', 'Putra (male)'), ('putri', 'Putri (female)'), ('campur', 'Campur (mixed)')], max_length=20)),
                ('facilities', models.JSONField(blank=True, default=list, help_text='e.g. ["wifi", "ac", "parkir"]')),
                ('photos', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('reported_by', models.CharField(blank=True, max_length=150)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(default='driving', max_length=20)),
                ('distance_m', models.FloatField()),
                ('duration_s', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('boarding_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.boardinghouse')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.faculty')),
            ],
            options={
                'unique_together': {('boarding_house', 'faculty', 'profile')},
            },
        ),
    ]
