# Generated by Django 6.1 on 2026-09-20 00:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional label, e.g. an intersection name', max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='condition',
            field=models.CharField(choices=[('fair', 'Fair'), ('poor', 'Poor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326),
        ),
        migrations.CreateModel(
            name='RoadEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='listings.roadnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='listings.roadnode')),
            ],
        ),
    ]
