# Generated by Django 6.1 on 2026-09-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_roadnode_alter_roadsegment_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadnode',
            name='osm_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
